const ADD_POST = "ADD_POST";
const EDIT_POST = "EDIT_POST";
const REMOVE_POST = "REMOVE_POST";
const ADD_COMMENT = "ADD_COMMENT";
const REMOVE_COMMENT = "REMOVE_COMMENT";

export {ADD_COMMENT, ADD_POST, EDIT_POST, REMOVE_COMMENT, REMOVE_POST}
